"use client"
//
import './globals.css'
// import "../../style/globalTheme/globalThem.css";
import { Inter } from 'next/font/google'


import { Providers } from './redux/providers';

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import Navbar from './nav/page';
import { AuthProvider } from '../../context/AuthContext';

config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Know Your Home',
  description: 'Generated by Know Your Home',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
      <AuthProvider>
        <Providers>
          <Navbar/>
        {children}
        </Providers>
        </AuthProvider>
      </body>
    </html>
  )
}
